using AngleSharp.Html.Parser;
using AngleSharp.Dom;
using Dapper;
using Npgsql;
using System.Security.Cryptography;
using System.Text;
using System.Text.RegularExpressions;
using TestJob.Constants;
using TestJob.Factories;
using TestJob.Interfaces;
using TestJob.Models;
using IConfiguration = Microsoft.Extensions.Configuration.IConfiguration;

namespace TestJob.Services
{
    public class TestJobService : ITestJobService
    {
        private readonly IConfiguration _configuration;
        private static readonly Regex EmailRegex = new(@"[a-zA-Z0-9._%+\-]+@[a-zA-Z0-9.\-]+\.[a-zA-Z]{2,}", RegexOptions.IgnoreCase | RegexOptions.CultureInvariant);

        public TestJobService(IConfiguration configuration)
        {
            _configuration = configuration;
        }

        public async Task<TestJobResponse> ProcessAsync(TestJobRequest model, CancellationToken cancellationToken)
        {
            if (!TryDecodeBase64(model.UrlBase64!, out var urlBytes))
            {
                return TestJobResponseFactory.Error(
                    TestJobErrorCodes.InvalidUrlBase64,
                    "Parameter 'url_b64' contains invalid Base64 data.");
            }

            if (!TryDecodeBase64(model.PageBase64!, out var pageBytes))
            {
                return TestJobResponseFactory.Error(
                    TestJobErrorCodes.InvalidPageBase64,
                    "Parameter 'page_b64' contains invalid Base64 data.");
            }

            var decodedUrl = Encoding.UTF8.GetString(urlBytes);
            var decodedPage = Encoding.UTF8.GetString(pageBytes);

            var parser = new HtmlParser();

            var document = await parser.ParseDocumentAsync(decodedPage, cancellationToken);

            var selectedElements = document.QuerySelectorAll(model.Selector!);

            var emails = ExtractEmailsFromHtml(decodedPage);

            if (!TryDecryptAes256Ecb(
                model.EncryptedTextBytesBase64!, model.KeyBytesBase64!, out var decryptedText, out var errorCode, out var errorMessage))
            {
                return TestJobResponseFactory.Error(errorCode, errorMessage);
            }

            var attributeValues = await SaveElementsAsync(
                selectedElements,
                model.Attribute!,
                cancellationToken);

            return TestJobResponseFactory.Success(
                selectedElements.Length,
                emails.Count,
                decodedUrl,
                decryptedText,
                attributeValues,
                emails);
        }

        private async Task<List<string>> SaveElementsAsync(
            IEnumerable<IElement> selectedElements,
            string attributeName,
            CancellationToken cancellationToken)
        {
            var connectionString = _configuration.GetConnectionString("DefaultConnection");

            if (string.IsNullOrWhiteSpace(connectionString))
            {
                throw new InvalidOperationException("Connection string 'DefaultConnection' is not configured.");
            }

            await using var connection = new NpgsqlConnection(connectionString);

            await connection.OpenAsync(cancellationToken);

            await using var transaction = await connection.BeginTransactionAsync(cancellationToken);

            const string createTableSql = """
                CREATE TABLE IF NOT EXISTS elements
                (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    attribute TEXT NOT NULL,
                    html_content TEXT NOT NULL
                );
                """;

            await connection.ExecuteAsync(
                new CommandDefinition(
                    createTableSql,
                    transaction: transaction,
                    cancellationToken: cancellationToken));

            const string insertElementSql = """
                INSERT INTO elements
                (
                    attribute,
                    html_content
                )
                VALUES
                (
                    @Attribute,
                    @HtmlContent
                );
                """;

            var attributeValues = new List<string>();

            foreach (var element in selectedElements)
            {
                var attributeValue = element.GetAttribute(attributeName);

                if (attributeValue is null)
                {
                    continue;
                }

                attributeValues.Add(attributeValue);

                await connection.ExecuteAsync(
                    new CommandDefinition(
                        insertElementSql,
                        new
                        {
                            Attribute = attributeValue,
                            HtmlContent = element.OuterHtml
                        },
                        transaction: transaction,
                        cancellationToken: cancellationToken));
            }

            await transaction.CommitAsync(cancellationToken);

            return attributeValues;
        }

        private static bool TryDecodeBase64(string value, out byte[] result)
        {
            try
            {
                result = Convert.FromBase64String(value);
                return true;
            }
            catch (FormatException)
            {
                result = [];
                return false;
            }
        }

        private static List<string> ExtractEmailsFromHtml(string htmlContent)
        {
            return EmailRegex
                .Matches(htmlContent)
                .Select(match => match.Value)
                .ToList();
        }

        private static bool TryDecryptAes256Ecb(
            string encryptedTextBase64, string keyBase64, out string decryptedText, out string errorCode, out string errorMessage)
        {
            decryptedText = string.Empty;
            errorCode = string.Empty;
            errorMessage = string.Empty;

            if (!TryPrepareAesData(
                    encryptedTextBase64,
                    keyBase64,
                    out var encryptedText,
                    out var key,
                    out errorCode,
                    out errorMessage))
            {
                return false;
            }

            try
            {
                using var aes = Aes.Create();

                aes.KeySize = 256;
                aes.BlockSize = 128;
                aes.Key = key;
                aes.Mode = CipherMode.ECB;
                aes.Padding = PaddingMode.None;

                using var decryptor = aes.CreateDecryptor();

                var decryptedBytes = decryptor.TransformFinalBlock(
                    encryptedText,
                    0,
                    encryptedText.Length);

                decryptedText = Encoding.UTF8.GetString(decryptedBytes);

                return true;
            }
            catch (CryptographicException)
            {
                errorCode = TestJobErrorCodes.DecryptionError;
                errorMessage = "The encrypted text cannot be decrypted.";

                return false;
            }
        }

        private static bool TryPrepareAesData(
            string encryptedTextBase64,
            string keyBase64,
            out byte[] encryptedText,
            out byte[] key,
            out string errorCode,
            out string errorMessage)
        {
            encryptedText = [];
            key = [];
            errorCode = string.Empty;
            errorMessage = string.Empty;

            if (!TryDecodeBase64(keyBase64, out key))
            {
                errorCode = TestJobErrorCodes.InvalidKeyBase64;
                errorMessage =
                    "Parameter 'key_bytes_b64' contains invalid Base64 data.";

                return false;
            }

            if (key.Length != 32)
            {
                errorCode = TestJobErrorCodes.InvalidAesKey;
                errorMessage = "AES-256 key must contain exactly 32 bytes.";

                return false;
            }

            if (!TryDecodeBase64(encryptedTextBase64, out encryptedText))
            {
                errorCode = TestJobErrorCodes.InvalidEncryptedTextBase64;
                errorMessage =
                    "Parameter 'encrypted_text_bytes_b64' contains invalid Base64 data.";

                return false;
            }

            if (encryptedText.Length == 0 ||
                encryptedText.Length % 16 != 0)
            {
                errorCode = TestJobErrorCodes.InvalidEncryptedTextLength;
                errorMessage =
                    "Encrypted text length must be a non-zero multiple of 16 bytes.";

                return false;
            }

            return true;
        }
    }
}
